[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Manash", email = "manashlamichhane5@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi==0.141.1",
    "jinja2==3.1.6",
    "langchain-groq==1.1.3",
    "langgraph==1.2.0",
    "python-dotenv==1.2.2",
    "uvicorn==0.52.1",
]

[project.scripts]
agent = "agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
